AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: IOT Tst Template

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        LOG_LEVE: DEBUG
    Runtime: python3.9

Resources:
  AlexaSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - arn:aws:lambda:us-east-1:173334852312:layer:ask-sdk-for-python-36:1
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: lambdas/AlexaSkillLambda
      Environment:
      Description: Voice Interface of the IOT Project
      MemorySize: 128
      Timeout: 8
      Events:
        AlexaTrigger:
          Type: AlexaSkill
Metadata:
  Name: alexa-skills-lambda-function
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - SkillFunctionName
          - SkillDescription
        Label:
          default: Lambda Function
    ParameterLabels:
      SkillDescription:
        default: What should the function description be?
      SkillFunctionName:
        default: What should the function be named?
Outputs:
  AlexaSampleFunctionArn:
    Description: "IOT Lambda Function ARN"
    Value: !GetAtt AlexaSampleFunction.Arn
    Export: { Name: !Sub "${AWS::StackName}:AlexaSampleFunction:Arn" }
